/*
 * api
 *
 * <br/>https://pca.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package privateca

type ActivateSubCa struct {

	// Pem 형식 Ca 인증서
	CertPem *string `json:"certPem"`

	// Pem 형식 Ca 인증서 체인
	CaChainPem *string `json:"caChainPem"`
}
