/*
 * api
 *
 * <br/>https://pca.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package privateca

type AddCaUser struct {

	// 서브 계정의 Id No
	IdNo *string `json:"idNo"`
}
