/*
 * api
 *
 * <br/>https://pca.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package privateca

type CaInfo struct {

	// Ca Id
	CaId *int32 `json:"caId,omitempty"`

	// 별칭
	Alias *string `json:"alias,omitempty"`

	// Ca tag
	CaTag *string `json:"caTag,omitempty"`

	// CA 상태 변경
	Status *string `json:"status,omitempty"`

	// 상태 변경 일시
	StatusUpdateDate *float32 `json:"statusUpdateDate,omitempty"`

	// 등록 일시
	RgstDate *float32 `json:"rgstDate,omitempty"`

	// Ca 타입
	CaType *string `json:"caType,omitempty"`

	// 메모
	Memo *string `json:"memo,omitempty"`

	// 인증서 서명 개수
	SigningCount *float32 `json:"signingCount,omitempty"`

	UrlInfo *CaInfoUrlInfo `json:"urlInfo,omitempty"`
}
