/*
 * api
 *
 * <br/>https://pca.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package privateca

// 배포 Urls
type CaInfoUrlInfo struct {

	// Ca 배포 Url
	Ca *[]string `json:"ca,omitempty"`

	// Crl 배포 Url
	Crl *[]string `json:"crl,omitempty"`

	// Ocsp 질의 Url
	Ocsp *[]string `json:"ocsp,omitempty"`
}
