/*
 * api
 *
 * <br/>https://pca.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package privateca

type GetEndCertInfoResponseData struct {

	// 인증서 시리얼 번호
	SerialNo *string `json:"serialNo,omitempty"`

	// 인증서 이름
	CommonName *string `json:"commonName,omitempty"`

	// 인증서 유효 기간
	NotBeforeDate *float32 `json:"notBeforeDate,omitempty"`

	// 인증서 만료 기간
	NotAfterDate *float32 `json:"notAfterDate,omitempty"`

	// 공개키 알고리즘
	PublicKeyAlgorithm *string `json:"publicKeyAlgorithm,omitempty"`

	// 서명 알고리즘
	SignatureAlgorithm *string `json:"signatureAlgorithm,omitempty"`

	// Pem 형식 인증서
	CertPem *string `json:"certPem,omitempty"`

	// Pem 형식 Ca 인증서 체인
	CaChain *string `json:"caChain,omitempty"`

	// Ocsp Responder 인증서
	OcspResponder *string `json:"ocspResponder,omitempty"`
}
