/*
 * api
 *
 * <br/>https://pca.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package privateca

type ListCaResponseData struct {

	// 총 개수
	TotalCnt *float32 `json:"totalCnt,omitempty"`

	// 총 페이지 수
	TotalPageNo *float32 `json:"totalPageNo,omitempty"`

	// 현재 페이지
	CurrentPageNo *float32 `json:"currentPageNo,omitempty"`

	CaInfoList []*CreateCaResponseData `json:"caInfoList,omitempty"`
}
