/*
 * api
 *
 * <br/>https://pca.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package privateca

type ListCaUsersResponseData struct {

	// 로그인 Id
	LoginId *string `json:"loginId,omitempty"`

	// Member No
	MbrNo *string `json:"mbrNo,omitempty"`

	// Id No
	IdNo *string `json:"idNo,omitempty"`
}
