/*
 * api
 *
 * <br/>https://pca.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package privateca

type X509EndCertParameters struct {

	// 인증서 이름 혹은 도메인. 최대 64자 입력 가능
	CommonName *string `json:"commonName"`

	// 인증서의 다른 이름
	AltName *string `json:"altName,omitempty"`

	// 인증서에 해당하는 IP, \",\" 구분자 리스트
	Ip *string `json:"ip,omitempty"`

	// 인증서에 해당하는 URI, \",\" 구분자 리스트
	Uri *string `json:"uri,omitempty"`

	// 기타 인증서 정보, {OID};UTF8:{value} 포맷, \",\" 구분자 리스트
	Other *string `json:"other,omitempty"`

	// 국가
	Country *string `json:"country,omitempty"`

	// 회사
	Organization *string `json:"organization,omitempty"`

	// 조직
	OrganizationUnit *string `json:"organizationUnit,omitempty"`

	// 도시
	Locality *string `json:"locality,omitempty"`

	// 구/동
	StateProvince *string `json:"stateProvince,omitempty"`

	// 도로명
	StreetAddress *string `json:"streetAddress,omitempty"`

	// 우편번호
	PostalCode *string `json:"postalCode,omitempty"`

	// CSR 설정 값 사용 여부
	UseCnAsSan *bool `json:"useCnAsSan,omitempty"`

	// 키 용도
	KeyUsage []*string `json:"keyUsage,omitempty"`

	// 확장 키 용도
	ExtendedKeyUsage []*string `json:"extendedKeyUsage,omitempty"`
}
