apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-approve:ncloud-pca-issuer
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - signers
  verbs:
  - approve
  resourceNames:
  - ncloudpcaclusterissuers.privateca-issuer.ncloud.com/*
  - ncloudpcaissuers.privateca-issuer.ncloud.com/*

