# permissions for end users to view ncloudpcaclusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ncloudpcaclusterissuer-viewer-role
rules:
- apiGroups:
  - privateca-issuer.ncloud.com
  resources:
  - ncloudpcaclusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - privateca-issuer.ncloud.com
  resources:
  - ncloudpcaclusterissuers/status
  verbs:
  - get
