# permissions for end users to edit ncloudpcaclusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ncloudpcaclusterissuer-editor-role
rules:
- apiGroups:
  - privateca-issuer.ncloud.com
  resources:
  - ncloudpcaclusterissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - privateca-issuer.ncloud.com
  resources:
  - ncloudpcaclusterissuers/status
  verbs:
  - get
