//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Naver Cloud Platform.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NcloudCredentialsSecretReference) DeepCopyInto(out *NcloudCredentialsSecretReference) {
	*out = *in
	out.SecretReference = in.SecretReference
	in.AccessKeyIDSelector.DeepCopyInto(&out.AccessKeyIDSelector)
	in.SecretAccessKeySelector.DeepCopyInto(&out.SecretAccessKeySelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NcloudCredentialsSecretReference.
func (in *NcloudCredentialsSecretReference) DeepCopy() *NcloudCredentialsSecretReference {
	if in == nil {
		return nil
	}
	out := new(NcloudCredentialsSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NcloudPCAClusterIssuer) DeepCopyInto(out *NcloudPCAClusterIssuer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NcloudPCAClusterIssuer.
func (in *NcloudPCAClusterIssuer) DeepCopy() *NcloudPCAClusterIssuer {
	if in == nil {
		return nil
	}
	out := new(NcloudPCAClusterIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NcloudPCAClusterIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NcloudPCAClusterIssuerList) DeepCopyInto(out *NcloudPCAClusterIssuerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NcloudPCAClusterIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NcloudPCAClusterIssuerList.
func (in *NcloudPCAClusterIssuerList) DeepCopy() *NcloudPCAClusterIssuerList {
	if in == nil {
		return nil
	}
	out := new(NcloudPCAClusterIssuerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NcloudPCAClusterIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NcloudPCAIssuer) DeepCopyInto(out *NcloudPCAIssuer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NcloudPCAIssuer.
func (in *NcloudPCAIssuer) DeepCopy() *NcloudPCAIssuer {
	if in == nil {
		return nil
	}
	out := new(NcloudPCAIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NcloudPCAIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NcloudPCAIssuerCondition) DeepCopyInto(out *NcloudPCAIssuerCondition) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NcloudPCAIssuerCondition.
func (in *NcloudPCAIssuerCondition) DeepCopy() *NcloudPCAIssuerCondition {
	if in == nil {
		return nil
	}
	out := new(NcloudPCAIssuerCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NcloudPCAIssuerList) DeepCopyInto(out *NcloudPCAIssuerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NcloudPCAIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NcloudPCAIssuerList.
func (in *NcloudPCAIssuerList) DeepCopy() *NcloudPCAIssuerList {
	if in == nil {
		return nil
	}
	out := new(NcloudPCAIssuerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NcloudPCAIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NcloudPCAIssuerSpec) DeepCopyInto(out *NcloudPCAIssuerSpec) {
	*out = *in
	in.SecretRef.DeepCopyInto(&out.SecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NcloudPCAIssuerSpec.
func (in *NcloudPCAIssuerSpec) DeepCopy() *NcloudPCAIssuerSpec {
	if in == nil {
		return nil
	}
	out := new(NcloudPCAIssuerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NcloudPCAIssuerStatus) DeepCopyInto(out *NcloudPCAIssuerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]NcloudPCAIssuerCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NcloudPCAIssuerStatus.
func (in *NcloudPCAIssuerStatus) DeepCopy() *NcloudPCAIssuerStatus {
	if in == nil {
		return nil
	}
	out := new(NcloudPCAIssuerStatus)
	in.DeepCopyInto(out)
	return out
}
