apiVersion: privateca-issuer.ncloud.com/v1alpha1
kind: NcloudPCAIssuer
metadata:
  name: issuer-sample
spec:
  caTag: abcd1234-efgh5678
  ncloudApiGw: https://pca.apigw.ntruss.com
  keyType: RSA
  keyBits: '4096'
  secretRef:
    name: ncloud-secret
