apiVersion: privateca-issuer.ncloud.com/v1alpha1
kind: NcloudPCAClusterIssuer
metadata:
  name: clusterissuer-sample
spec:
  caTag: abcd1234-efgh5678
  region: public
  credentialsRef:
    name: ncloud-secret
    namespace: cert-manager
